const songs = [
  {
    title: "Smack That (ft. Eminem)",
    artist: "Akon",
    album: "Konvicted",
    id: "SmAkKo",
    added: false,
    uri: "2kQuhkFX7uSVepCD3h29g5",
  },
  {
    title: "Babydoll",
    artist: "Dominic Fike",
    album: "Don't Forget About Me, Demos",
    id: "BaDoDo",
    added: false,
    uri: "7yNf9YjeO5JXUE3JEBgnYc",
  },
  {
    title: "Planet Shrooms",
    artist: "Woodie Smalls",
    album: "Planet Shrooms",
    id: "PlWoPl",
    added: false,
    uri: "16OlG0GeSYrJZQpDd16i79",
  },
  {
    title: "November 18th",
    artist: "Drake",
    album: "So Far Gone",
    id: "NoDrSo",
    added: false,
    uri: "0JaVdpmiex2EP7bBzyKVTa",
  },
  {
    title: "Narcos",
    artist: "Freddie Gibbs",
    album: "Shadow of a Doubt",
    id: "NaFrSh",
    added: false,
    uri: "1lLffqf4fLFGfoa7BpokdB",
  },
  {
    title: "A Milli",
    artist: "Lil Wayne",
    album: "Tha Carter III",
    id: "AMLiTh",
    added: false,
    uri: "3uqinR4FCjLv28bkrTdNX5",
  },
  {
    title: "From Adam (ft. Lil Wayne)",
    artist: "The Game",
    album: "The Documentary 2.5",
    id: "FrThTh",
    added: false,
    uri: "1tcx5cpqdcwjy5Oo8rshs5",
  },
  {
    title: "Lodi Dodi (ft. Nancy Fletcher)",
    artist: "Snoop Dogg",
    album: "Doggystyle",
    id: "LoSnDo",
    added: false,
    uri: "6OtfwrzhIaIg6gmnzgPlu1",
  },
  {
    title: "Lately (ft. Bugus & Musa)",
    artist: "Russ",
    album: "Silence",
    id: "LaRuSi",
    added: false,
    uri: "4bI8a3bXcI0CIobu3M0F3W",
  },
  {
    title: "Coming Back (ft. Mac Miller)",
    artist: "Domo Genesis",
    album: "Genesis",
    id: "CoDoGe",
    added: false,
    uri: "1WsRuvitfegWXQJKRgRZrj",
  },
  {
    title: "Half Manne Half Cocaine",
    artist: "Freddie Gibbs",
    album: "Bandana",
    id: "HaFrBa",
    added: false,
    uri: "5jqpm69UgQa1OSNhj8rjn4",
  },
  {
    title: "Bat Box 9",
    artist: "Houdinne",
    album: "Damn EP",
    id: "BaHoDa",
    added: false,
    uri: "0rm61xV00FWmZv5UD72lcr",
  },
  {
    title: "BABY NUEVA",
    artist: "Bad Bunny",
    album: "nadie sabe lo que va a pasar mañana",
    id: "BABana",
    added: false,
    uri: "3NhstUmrlhaN1M6hP8zMbb",
  },
  {
    title: "Rap Trash",
    artist: "Koi Child",
    album: "Koi Child",
    id: "RaKoKo",
    added: false,
    uri: "3cf8J6iohKq7hLSirL3Pb6",
  },
  {
    title: "Momentz (ft. De La Soul)",
    artist: "Gorillaz",
    album: "Humanz (Deluxe)",
    id: "MoGoHu",
    added: false,
    uri: "2RCp9QBnFSxdKe8RD4xF8s",
  },
  {
    title: "What They Want",
    artist: "Russ",
    album: "What They Want",
    id: "WhRuWh",
    added: false,
    uri: "3pndPhlQWjuSoXhcIIdBjv",
  },
  {
    title: "Hello (ft. Dr.Dre & MC Ren)",
    artist: "Ice Cube",
    album: "War & Peace vol. 2 (The Peace Disc)",
    id: "HeIcWa",
    added: false,
    uri: "60uesDF4UyLUs61FgiDkdp",
  },
  {
    title: "Where Ya At (ft. Drake)",
    artist: "Future",
    album: "DS2 (Deluxe)",
    id: "WhFuDS",
    added: false,
    uri: "5nN8BwAQDJDguq7Dpd3JQQ",
  },
  {
    title: "Fall in Love (ft. Ciscero)",
    artist: "Goldlink",
    album: "Fall in Love",
    id: "FaGoFa",
    added: false,
    uri: "2RISD4aJrioDB54exm5WWM",
  },
];

const playlist = {
  name: "",
  songs: [],
  allUris: [],
};

export { songs, playlist };
