const songs = [
  {
    title: "Smack That (ft. Eminem)",
    artist: "Akon",
    album: "Konvicted",
    id: "SmAkKo",
    added: false,
  },
  {
    title: "Babydoll",
    artist: "Dominic Fike",
    album: "Don't Forget About Me, Demos",
    id: "BaDoDo",
    added: false,
  },
  {
    title: "Planet Shrooms",
    artist: "Woodie Smalls",
    album: "Planet Shrooms",
    id: "PlWoPl",
    added: false,
  },
  {
    title: "November 18th",
    artist: "Drake",
    album: "So Far Gone",
    id: "NoDrSo",
    added: false,
  },
  {
    title: "Narcos",
    artist: "Freddie Gibbs",
    album: "Shadow of a Doubt",
    id: "NaFrSh",
    added: false,
  },
  {
    title: "A Milli",
    artist: "Lil Wayne",
    album: "Tha Carter III",
    id: "AMLiTh",
    added: false,
  },
  {
    title: "From Adam (ft. Lil Wayne)",
    artist: "The Game",
    album: "The Documentary 2.5",
    id: "FrThTh",
    added: false,
  },
  {
    title: "Lodi Dodi (ft. Nancy Fletcher)",
    artist: "Snoop Dogg",
    album: "Doggystyle",
    id: "LoSnDo",
    added: false,
  },
  {
    title: "Lately (ft. Bugus & Musa)",
    artist: "Russ",
    album: "Silence",
    id: "LaRuSi",
    added: false,
  },
  {
    title: "Coming Back (ft. Mac Miller)",
    artist: "Domo Genesis",
    album: "Genesis",
    id: "CoDoGe",
    added: false,
  },
  {
    title: "Half Manne Half Cocaine",
    artist: "Freddie Gibbs",
    album: "Bandana",
    id: "HaFrBa",
    added: false,
  },
  {
    title: "Bat Box 9",
    artist: "Houdinne",
    album: "Damn EP",
    id: "BaHoDa",
    added: false,
  },
  {
    title: "BABY NUEVA",
    artist: "Bad Bunny",
    album: "nadie sabe lo que va a pasar mañana",
    id: "BABana",
    added: false,
  },
  {
    title: "Rap Child",
    artist: "Koi Child",
    album: "Koi Child",
    id: "RaKoKo",
    added: false,
  },
  {
    title: "Momentz (ft. De La Soul)",
    artist: "Gorillaz",
    album: "Humanz (Deluxe)",
    id: "MoGoHu",
    added: false,
  },
  {
    title: "What They Want",
    artist: "Russ",
    album: "What They Want",
    id: "WhRuWh",
    added: false,
  },
  {
    title: "Hello (ft. Dr.Dre & MC Ren)",
    artist: "Ice Cube",
    album: "War & Peace vol. 2 (The Peace Disc)",
    id: "HeIcWa",
    added: false,
  },
  {
    title: "Where Ya At (ft. Drake)",
    artist: "Future",
    album: "DS2 (Deluxe)",
    id: "WhFuDS",
    added: false,
  },
  {
    title: "Fall in Love (ft. Ciscero)",
    artist: "Goldlink",
    album: "Fall in Love",
    id: "FaGoFa",
    added: false,
  },
];

const playlist = {
  name: "",
  songs: [],
};

export { songs, playlist };
